### ISSUE TITLE
How will we store scenarios backgrounds in file hierarchy.

### ISSUE THREAD

**Issue by miseb** [machpavel/autickax#272]
Now we have
\images\backgrounds\backgroundX.png

However backgrounds are related with scenarios now.
E.g. backgroundDesert5.png, backgroundforest6.png etc.
Is it just designer thing to know what to use in what scenario? Should it be split at least in editor.

Maybe it would be great not to rename files and load dynamically all files from backgrounds folder into some array and then provide it to level designer.

**Comment by machpavel** [comment]
Scenarios and other things related will be stored in a Levels folder. Configuration file for the level will be included there as well.
